name: Release test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Only for testing of the release environment.
  semantic:
    name: Semantic-Release-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install @semantic-release/changelog @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git semantic-release/release-notes-generator

      - name: Git WTF?
        run: |
          which git
          git status
          ls

      - name: Git fetch tags (Workaround shallow clones)
        run: git fetch --tags

      - name: Git describe??
        run: |
          git rev-list --tags --max-count=1
          git describe --tags
          git describe --tags $(git rev-list --tags --max-count=1)

      - name: Get the last tag via git (before release)
        run: git describe --tags $(git rev-list --tags --max-count=1)

      - name: Release (Dry-Run)
        run: npx semantic-release -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the last tag via git (after release)
        run: git describe --tags $(git rev-list --tags --max-count=1)
